version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network
  
  frontend:
    build: 
      context: ../frontend
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL} # LĂSĂM AȘA. E PERFECT!
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    build:
      context: ../backend
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS="-Xmx512m -Xms256m"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AI_API_KEYS=${AI_API_KEYS}
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80" 
    depends_on:
      - postgres
    networks:
      - db-network

volumes:
  postgres_data:

networks:
  db-network:
    driver: bridge